@startuml
allow_mixing
' left to right direction
namespace CreateCompanyCollaboration{
actor User
User --> CreateCompanyView
    note on link
        createCompany()
    end note
CreateCompanyView --> CreateCompanyController
    note on link
        interact(name)
    end note
CreateCompanyController --> Company
    note on link
        execute(name)
    end note
}
@enduml