@startuml
namespace DomainModel{
class User
class Company
class Headquarter
class Map
class GoogleMaps
class Image
class Sensor
class RegisterLog

User  o--> "*" Sensor
User o--> "*" Company
Company o--> "*" Headquarter
Headquarter o--> "*" Map
GoogleMaps -up-|> Map
Image -up-|> Map

Sensor --> "1" Map
Sensor --> "*" RegisterLog
Map --> "*" RegisterLog
}
@enduml