@startuml
namespace DomainModel{
class User
class Company
class Headquarter
class Map
class GoogleMaps
class Image
class Sensor
class RegisterLog

User  *--> "*" Sensor
User *--> "*" Company
Company *--> "*" Headquarter
Headquarter *--> "*" Map
Map -down-|> GoogleMaps
Map -down-|> Image

Sensor ..> "1" Map
Sensor --> "*" RegisterLog
}
@enduml