@startuml
'title Domain model
namespace DomainModel{
class User
class Company
class Headquarter
class Map
class GoogleMaps
class Image
class Sensor
class RegisterLog

User "1" *--> "n" Sensor
User "1" *--> "n" Company
Company "1" *--> "n" Headquarter
Headquarter "1" *--> "n" Map
Map -down-|> GoogleMaps
Map -down-|> Image

Sensor ..> Map

Sensor ..> RegisterLog
}
@enduml