@startuml
allowmixing
namespace useCases{
left to right direction
actor User

usecase CreateSensor
usecase ReadSensor
usecase UpdateSensor
usecase DeleteSensor
usecase AddSensorToMap
usecase AddSensorToStock
usecase MoveSensor

usecase ShowState
usecase PrintState
usecase SendState

usecase CreateCompany
usecase ReadCompany
usecase UpdateCompany
usecase DeleteCompany

usecase CreateHeadquarter
usecase ReadHeadquarter
usecase UpdateHeadquarter
usecase DeleteHeadquarter

usecase CreateMap
usecase ReadMap
usecase UpdateMap
usecase DeleteMap

User --> CreateSensor
CreateSensor ..> ReadSensor  : "<<include>>"
User --> UpdateSensor
UpdateSensor ..> ReadSensor  : "<<include>>"
User --> DeleteSensor
DeleteSensor ..> ReadSensor  : "<<include>>"

User --> AddSensorToMap
User --> AddSensorToStock

User --> MoveSensor

User --> CreateCompany
CreateCompany ..> ReadCompany : "<<include>>"
User --> UpdateCompany
UpdateCompany ..> ReadCompany : "<<include>>"
User --> DeleteCompany
DeleteCompany ..> ReadCompany : "<<include>>"

User --> CreateHeadquarter
CreateHeadquarter ..> ReadHeadquarter : "<<include>>"
User --> UpdateHeadquarter
UpdateHeadquarter ..> ReadHeadquarter : "<<include>>"
User --> DeleteHeadquarter
DeleteHeadquarter ..> ReadHeadquarter : "<<include>>"

User --> CreateMap
CreateMap  ..> ReadMap : "<<include>>"
User --> UpdateMap
UpdateMap  ..> ReadMap : "<<include>>"
User --> DeleteMap
DeleteMap  ..> ReadMap : "<<include>>"

User --> ShowState
User --> PrintState
User --> SendState
}
@enduml