@startuml
'title EditConfigCollaborationDiagram
namespace CreateCompanyCollaboration{
allow_mixing
' left to right direction

actor User

object CreateCompanyView
object CreateCompanyController
object CreateCompanyModel

User --> CreateCompanyView
note on link
    setName(param)
end note
CreateCompanyView ..> CreateCompanyController : interact(EditConfigController)

CreateCompanyCollaboration --> CreateCompanyModel

}
@enduml