@startuml
title UseCaseContext

state INITIAL
state OPENED_APPLICATION
state COMPANY_CREATED
state HEADQUARTER_CREATED
state MAP_CREATED
state SENSOR_CREATED
state STATS_GENERATED

[*] --> INITIAL

INITIAL --> OPENED_APPLICATION
note on link
    Login (not on this version)
end note

OPENED_APPLICATION --> COMPANY_CREATED
    note on link
        CreateCompany
    end note
COMPANY_CREATED --> COMPANY_CREATED
note on link
    ReadCompany
    UpdateCompany
    DeleteCompany
end note

COMPANY_CREATED --> HEADQUARTER_CREATED
    note on link
        CreateHeadquarter
    end note

HEADQUARTER_CREATED --> HEADQUARTER_CREATED
    note on link
        ReadHeadquarter
        UpdateHeadquarter
        DeleteHeadquarter
    end note

HEADQUARTER_CREATED --> MAP_CREATED
    note on link
        CreateMap
    end note

MAP_CREATED --> MAP_CREATED
    note on link
        ReadMap
        UpdateMap
        DeleteMap
    end note

MAP_CREATED --> STATS_GENERATED

OPENED_APPLICATION --> SENSOR_CREATED
    note on link
        CreateSensor
    end note

SENSOR_CREATED --> SENSOR_CREATED
    note on link
        ReadSensor
        UpdateSensor
        DeleteSensor
        AddSensorToMap
        AddSensorToStock
    end note

COMPANY_CREATED --> [*]
      note on link
          Logout (not on this version)
      end note

HEADQUARTER_CREATED --> [*]
      note on link
          Logout (not on this version)
      end note

MAP_CREATED --> [*]
      note on link
          Logout (not on this version)
      end note

SENSOR_CREATED --> STATS_GENERATED
       note on link
           ShowState
           PrintState
           SendState
       end note

STATS_GENERATED --> STATS_GENERATED
    note on link
        SendState
        ShowState
        PrintState
    end note

STATS_GENERATED --> [*]
      note on link
          Logout (not on this version)
      end note
@enduml